704: 704.cpp
	g++ -ggdb -Wall -o ./bin/704 704.cpp

35: 35.cpp
	g++ -ggdb -Wall -o ./bin/35 35.cpp

27: 27.cpp
	g++ -ggdb -Wall -o ./bin/27 27.cpp

977: 977.cpp
	g++ -ggdb -Wall -o ./bin/977 977.cpp

209: 209.cpp
	g++ -ggdb -Wall -o ./bin/209 209.cpp

review704: review704.cpp
	g++ -ggdb -Wall -o ./bin/review704 review704.cpp

clean:
	rm -f ./bin/704 ./bin/35 ./bin/review704 ./bin/27 ./bin/977 ./bin/209 
